name: butterflyui_runtime
description: "ButterflyUI runtime (Flutter) controlled by Python via JSON remote."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel:
  webview_windows:
  native_preview_host:
    path: packages/native_preview_host
  animations:
  file_picker:
  flutter_markdown_plus:
  flutter_svg:
  media_kit:
  media_kit_libs_windows_audio:
  media_kit_libs_windows_video:
  media_kit_video:
  material_color_utilities:
  flutter_staggered_grid_view:
  highlight:
  google_fonts:
  flutter_animate:
  cached_network_image:
  another_flushbar:
  fluttertoast:
  mime:
  rive:
  lottie:
  visibility_detector:
  palette_generator_master:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/
