from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Mapping
from typing import Any

__all__ = [
    "IconData",
    "ICON_NAMES",
    "ICON_SET",
    "icon_names",
    "is_icon_name",
    "normalize_icon_name",
    "normalize_icon_value",
    "suggest_icon_names",
]


@dataclass(frozen=True, slots=True)
class IconData:
    """Typed icon descriptor used by Python-side icon registry helpers."""

    name: str
    codepoint: int | None = None


def normalize_icon_name(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = value.strip().lower().replace("-", "_").replace(" ", "_")
    return normalized or None


# Keep the registry fully inside the Python package so installed users do not
# depend on Flutter-side source files or metadata paths.
ICON_NAMES: tuple[str, ...] = (
    "add",
    "add_box",
    "add_circle",
    "add_link",
    "add_photo",
    "alarm",
    "analytics",
    "anchor",
    "android",
    "apple",
    "apps",
    "archive",
    "arrow_back",
    "arrow_drop_down",
    "arrow_drop_up",
    "arrow_downward",
    "arrow_down",
    "arrow_forward",
    "arrow_left",
    "arrow_right",
    "arrow_upward",
    "arrow_up",
    "assignment",
    "attach_file",
    "attachment",
    "audiotrack",
    "auto_awesome",
    "backspace",
    "backup",
    "bar_chart",
    "battery_charging",
    "battery_full",
    "beach",
    "bed",
    "bluetooth",
    "bolt",
    "bookmark",
    "bookmark_add",
    "bug",
    "build",
    "calendar",
    "call",
    "camera",
    "cancel",
    "car",
    "category",
    "chat",
    "check",
    "check_box",
    "check_box_outline",
    "check_circle",
    "checklist",
    "chevron_down",
    "chevron_left",
    "chevron_right",
    "chevron_up",
    "circle",
    "close",
    "cloud",
    "cloud_done",
    "cloud_download",
    "cloud_upload",
    "code",
    "coffee",
    "color_lens",
    "comment",
    "compass",
    "computer",
    "construction",
    "contact_mail",
    "copy",
    "copy_all",
    "dashboard",
    "data",
    "delete",
    "delete_forever",
    "description",
    "document",
    "download",
    "drag",
    "draw",
    "edit",
    "email",
    "equalizer",
    "error",
    "event",
    "explore",
    "extension",
    "face",
    "favorite",
    "feedback",
    "file",
    "file_copy",
    "filter",
    "filter_list",
    "fingerprint",
    "flag",
    "flight",
    "folder",
    "folder_open",
    "forum",
    "fullscreen",
    "fullscreen_exit",
    "functions",
    "gamepad",
    "gavel",
    "gif",
    "grade",
    "grid",
    "group",
    "handyman",
    "help",
    "history",
    "home",
    "hourglass",
    "http",
    "image",
    "info",
    "insights",
    "inventory",
    "key",
    "keyboard",
    "label",
    "language",
    "laptop",
    "launch",
    "lightbulb",
    "link",
    "list",
    "lock",
    "lock_open",
    "login",
    "logout",
    "mail",
    "map",
    "menu",
    "mic",
    "monitor",
    "more",
    "more_vert",
    "movie",
    "music",
    "new",
    "night",
    "notifications",
    "notifications_active",
    "notifications_off",
    "palette",
    "pause",
    "payment",
    "pending",
    "percent",
    "person",
    "person_add",
    "pets",
    "photo",
    "play",
    "play_circle",
    "print",
    "privacy",
    "public",
    "qr_code",
    "question_answer",
    "radio_checked",
    "radio_unchecked",
    "refresh",
    "remove",
    "remove_circle",
    "repeat",
    "reply",
    "report",
    "rocket",
    "route",
    "save",
    "save_alt",
    "schedule",
    "school",
    "science",
    "search",
    "send",
    "share",
    "shield",
    "shop",
    "shopping_cart",
    "shuffle",
    "settings",
    "star",
    "star_half",
    "stop",
    "storage",
    "success",
    "sun",
    "support",
    "swap",
    "sync",
    "table",
    "tag",
    "task",
    "terminal",
    "thumb_up",
    "time",
    "today",
    "toggle_off",
    "toggle_on",
    "translate",
    "trending_down",
    "trending_up",
    "tune",
    "undo",
    "update",
    "upload",
    "upload_file",
    "verified",
    "video",
    "video_call",
    "visibility",
    "visibility_off",
    "volume_off",
    "volume_up",
    "vpn_key",
    "wallet",
    "warning",
    "watch",
    "web",
    "wifi",
    "work",
    "plus",
    "plus_circle",
    "plus_box",
    "minus",
    "minus_circle",
    "x",
    "x_circle",
    "cancel_circle",
    "trash",
    "trash_forever",
    "bin",
    "copy_clipboard",
    "duplicate",
    "clipboard",
    "redo",
    "fast_forward",
    "rewind",
    "hamburger",
    "kebab",
    "ellipsis",
    "ellipsis_vertical",
    "caret_down",
    "caret_up",
    "caret_left",
    "caret_right",
    "chevron_down_small",
    "chevron_up_small",
    "house",
    "house_filled",
    "user",
    "user_plus",
    "users",
    "profile",
    "avatar",
    "gear",
    "cog",
    "slider",
    "adjust",
    "funnel",
    "funnel_list",
    "favourite",
    "heart",
    "bookmark_outline",
    "bookmark_plus",
    "pin",
    "tag_outline",
    "price_tag",
    "ticket",
    "label_outline",
    "bell",
    "bell_off",
    "bell_active",
    "alert",
    "alert_outline",
    "danger",
    "danger_outline",
    "info_outline",
    "question",
    "question_outline",
    "shield_outline",
    "security",
    "lock_outline",
    "unlock",
    "unlock_outline",
    "key_outline",
    "scan",
    "qr",
    "code_outline",
    "terminal_outline",
    "console",
    "braces",
    "database",
    "server",
    "cloud_done_outline",
    "cloud_upload_outline",
    "cloud_download_outline",
    "upload_outline",
    "download_outline",
    "upload_cloud",
    "download_cloud",
    "folder_outline",
    "folder_open_outline",
    "document_text",
    "document_outline",
    "file_outline",
    "paperclip",
    "clip",
    "image_outline",
    "photo_outline",
    "video_outline",
    "movie_outline",
    "audio",
    "audio_outline",
    "music_note",
    "mic_outline",
    "volume_high",
    "volume_mute",
    "mute",
    "camera_outline",
    "camera_video",
    "phone",
    "phone_call",
    "mail_outline",
    "email_outline",
    "chat_outline",
    "message",
    "message_outline",
    "forum_outline",
    "send_outline",
    "reply_outline",
    "share_outline",
    "calendar_outline",
    "clock",
    "clock_outline",
    "timer",
    "schedule_outline",
    "today_outline",
    "event_outline",
    "search_outline",
    "zoom_plus",
    "zoom_minus",
    "fullscreen_open",
    "fullscreen_close",
    "visibility_outline",
    "eye",
    "eye_off",
    "hidden",
    "star_outline",
    "star_half_outline",
    "rating",
    "check_outline",
    "checkmark",
    "checkmark_circle",
    "success_outline",
    "radio_on",
    "radio_off",
    "checkbox_on",
    "checkbox_off",
    "toggle_enabled",
    "toggle_disabled",
    "sparkles",
    "magic",
    "palette_outline",
    "paint",
    "brush",
    "shape",
    "grid_outline",
    "table_outline",
    "dashboard_outline",
    "chart_bar",
    "chart_line",
    "insight",
    "layers",
    "map_outline",
    "route_outline",
    "location",
    "location_pin",
    "compass_outline",
    "navigation",
    "globe",
    "planet",
    "wifi_outline",
    "bluetooth_outline",
    "battery",
    "battery_outline",
    "battery_charging_outline",
    "laptop_outline",
    "computer_outline",
    "monitor_outline",
    "watch_outline",
    "android_logo",
    "apple_logo",
    "cart",
    "bag",
    "shop_outline",
    "wallet_outline",
    "payment_outline",
    "gift",
    "gift_outline",
    "rocket_outline",
    "launch_outline",
    "sun_outline",
    "moon",
    "night_mode",
    "light_mode",
    "work_outline",
    "briefcase",
    "support_outline",
    "helpdesk",
    "bug_outline",
    "puzzle",
    "extension_outline",
    "zoom_in",
    "zoom_out",
)
ICON_SET: frozenset[str] = frozenset(ICON_NAMES)


def icon_names() -> tuple[str, ...]:
    return ICON_NAMES


def is_icon_name(value: str | None) -> bool:
    normalized = normalize_icon_name(value)
    return normalized in ICON_SET if normalized is not None else False


def suggest_icon_names(value: str | None, *, limit: int = 8) -> list[str]:
    normalized = normalize_icon_name(value)
    if not normalized:
        return []

    starts_with = [name for name in ICON_NAMES if name.startswith(normalized)]
    if len(starts_with) >= limit:
        return starts_with[:limit]

    contains = [
        name
        for name in ICON_NAMES
        if normalized in name and name not in starts_with
    ]
    return (starts_with + contains)[:limit]


def normalize_icon_value(value: Any, *, strict: bool = False) -> Any:
    if value is None:
        return None

    if isinstance(value, bool):
        return value

    if isinstance(value, int):
        return value

    if isinstance(value, str):
        normalized = normalize_icon_name(value)
        if normalized is None:
            return value
        if strict and normalized not in ICON_SET:
            suggestions = suggest_icon_names(normalized)
            if suggestions:
                suggestion_text = ", ".join(suggestions)
                raise ValueError(
                    f"Unknown icon name '{value}'. Did you mean: {suggestion_text}?"
                )
            raise ValueError(f"Unknown icon name '{value}'.")
        return normalized

    if isinstance(value, Mapping):
        out = dict(value)
        for key in ("icon", "name", "value", "glyph"):
            if key in out:
                out[key] = normalize_icon_value(out[key], strict=strict)
        return out

    return value
