from __future__ import annotations

from .control import (
    CODE_EDITOR_DEFAULT_ENGINE,
    CODE_EDITOR_DEFAULT_WEBVIEW_ENGINE,
    CODE_EDITOR_EVENTS,
    CODE_EDITOR_MODULES,
    CODE_EDITOR_REGISTRY_MANIFEST_LISTS,
    CODE_EDITOR_REGISTRY_ROLE_ALIASES,
    CODE_EDITOR_SCHEMA_VERSION,
    CODE_EDITOR_STATES,
)

SCHEMA_VERSION = CODE_EDITOR_SCHEMA_VERSION
DEFAULT_ENGINE = CODE_EDITOR_DEFAULT_ENGINE
DEFAULT_WEBVIEW_ENGINE = CODE_EDITOR_DEFAULT_WEBVIEW_ENGINE
MODULES = tuple(sorted(CODE_EDITOR_MODULES))
STATES = tuple(sorted(CODE_EDITOR_STATES))
EVENTS = tuple(sorted(CODE_EDITOR_EVENTS))
REGISTRY_ROLE_ALIASES = dict(CODE_EDITOR_REGISTRY_ROLE_ALIASES)
REGISTRY_MANIFEST_LISTS = dict(CODE_EDITOR_REGISTRY_MANIFEST_LISTS)
MODULE_ALIASES: dict[str, str] = {}

__all__ = [
    "SCHEMA_VERSION",
    "DEFAULT_ENGINE",
    "DEFAULT_WEBVIEW_ENGINE",
    "MODULES",
    "STATES",
    "EVENTS",
    "REGISTRY_ROLE_ALIASES",
    "REGISTRY_MANIFEST_LISTS",
    "MODULE_ALIASES",
]

