from __future__ import annotations

from .control import (
    GALLERY_EVENTS,
    GALLERY_MODULES,
    GALLERY_REGISTRY_MANIFEST_LISTS,
    GALLERY_REGISTRY_ROLE_ALIASES,
    GALLERY_SCHEMA_VERSION,
    GALLERY_STATES,
)

SCHEMA_VERSION = GALLERY_SCHEMA_VERSION
MODULES = tuple(sorted(GALLERY_MODULES))
STATES = tuple(sorted(GALLERY_STATES))
EVENTS = tuple(sorted(GALLERY_EVENTS))
REGISTRY_ROLE_ALIASES = dict(GALLERY_REGISTRY_ROLE_ALIASES)
REGISTRY_MANIFEST_LISTS = dict(GALLERY_REGISTRY_MANIFEST_LISTS)
MODULE_ALIASES: dict[str, str] = {}

__all__ = [
    "SCHEMA_VERSION",
    "MODULES",
    "STATES",
    "EVENTS",
    "REGISTRY_ROLE_ALIASES",
    "REGISTRY_MANIFEST_LISTS",
    "MODULE_ALIASES",
]

