from __future__ import annotations

from .control import (
    SKINS_DEFAULT_NAMES,
    SKINS_DEFAULT_PRESETS,
    SKINS_EVENTS,
    SKINS_MODULE_ALIASES,
    SKINS_MODULES,
    SKINS_REGISTRY_MANIFEST_LISTS,
    SKINS_REGISTRY_ROLE_ALIASES,
    SKINS_SCHEMA_VERSION,
    SKINS_STATES,
)

SCHEMA_VERSION = SKINS_SCHEMA_VERSION
MODULES = tuple(sorted(SKINS_MODULES))
MODULE_ALIASES = dict(SKINS_MODULE_ALIASES)
STATES = tuple(sorted(SKINS_STATES))
EVENTS = tuple(sorted(SKINS_EVENTS))
REGISTRY_ROLE_ALIASES = dict(SKINS_REGISTRY_ROLE_ALIASES)
REGISTRY_MANIFEST_LISTS = dict(SKINS_REGISTRY_MANIFEST_LISTS)
DEFAULT_NAMES = tuple(SKINS_DEFAULT_NAMES)
DEFAULT_PRESETS = tuple(SKINS_DEFAULT_PRESETS)

__all__ = [
    "SCHEMA_VERSION",
    "MODULES",
    "MODULE_ALIASES",
    "STATES",
    "EVENTS",
    "REGISTRY_ROLE_ALIASES",
    "REGISTRY_MANIFEST_LISTS",
    "DEFAULT_NAMES",
    "DEFAULT_PRESETS",
]

