from __future__ import annotations

from .capabilities import (
    ACTION_PROPS,
    ALL_CAPABILITY_PROPS,
    BUTTON_PROPS,
    CAPABILITY_PROP_NAMES,
    CHILD_PROPS,
    CORE_PROPS,
    EFFECT_PROPS,
    EVENT_NAMES,
    FOCUS_PROPS,
    FORM_FIELD_PROPS,
    INPUT_PROPS,
    LAYOUT_PROPS,
    MOTION_PROPS,
    OVERLAY_PROPS,
    PROP_CAPABILITY_OWNERS,
    SCROLL_PROPS,
    SELECTION_PROPS,
    SURFACE_PROPS,
    TOGGLE_PROPS,
    VISUAL_CAPABILITY_PROPS,
)
from .common_events import COMMON_EVENT_NAMES
from .common_props import COMMON_CORE_PROPS, COMMON_LAYOUT_PROPS, COMMON_STYLE_PROPS
from .registry import (
    CONTROL_SPECS,
    ControlSpec,
    EventSpec,
    PropSpec,
    control_category_map,
    control_specs_for_category,
    get_control_spec,
    iter_control_specs,
)

__all__ = [
    "COMMON_CORE_PROPS",
    "COMMON_LAYOUT_PROPS",
    "COMMON_STYLE_PROPS",
    "COMMON_EVENT_NAMES",
    "CORE_PROPS",
    "LAYOUT_PROPS",
    "SURFACE_PROPS",
    "MOTION_PROPS",
    "EFFECT_PROPS",
    "CHILD_PROPS",
    "FOCUS_PROPS",
    "INPUT_PROPS",
    "FORM_FIELD_PROPS",
    "SELECTION_PROPS",
    "TOGGLE_PROPS",
    "SCROLL_PROPS",
    "OVERLAY_PROPS",
    "ACTION_PROPS",
    "BUTTON_PROPS",
    "EVENT_NAMES",
    "CAPABILITY_PROP_NAMES",
    "PROP_CAPABILITY_OWNERS",
    "ALL_CAPABILITY_PROPS",
    "VISUAL_CAPABILITY_PROPS",
    "PropSpec",
    "EventSpec",
    "ControlSpec",
    "CONTROL_SPECS",
    "get_control_spec",
    "iter_control_specs",
    "control_specs_for_category",
    "control_category_map",
]
