from __future__ import annotations

from .control import (
    CANDY_EVENTS,
    CANDY_MODULES,
    CANDY_REGISTRY_MANIFEST_LISTS,
    CANDY_REGISTRY_ROLE_ALIASES,
    CANDY_SCHEMA_VERSION,
    CANDY_STATES,
)

SCHEMA_VERSION = CANDY_SCHEMA_VERSION
MODULES = tuple(sorted(CANDY_MODULES))
STATES = tuple(sorted(CANDY_STATES))
EVENTS = tuple(sorted(CANDY_EVENTS))
REGISTRY_ROLE_ALIASES = dict(CANDY_REGISTRY_ROLE_ALIASES)
REGISTRY_MANIFEST_LISTS = dict(CANDY_REGISTRY_MANIFEST_LISTS)
MODULE_ALIASES: dict[str, str] = {}

__all__ = [
    "SCHEMA_VERSION",
    "MODULES",
    "STATES",
    "EVENTS",
    "REGISTRY_ROLE_ALIASES",
    "REGISTRY_MANIFEST_LISTS",
    "MODULE_ALIASES",
]

