from __future__ import annotations

from .layout import CONTROL_SPECS as LAYOUT_CONTROL_SPECS
from .display import CONTROL_SPECS as DISPLAY_CONTROL_SPECS
from .inputs import CONTROL_SPECS as INPUT_CONTROL_SPECS
from .data import CONTROL_SPECS as DATA_CONTROL_SPECS
from .navigation import CONTROL_SPECS as NAVIGATION_CONTROL_SPECS
from .overlay import CONTROL_SPECS as OVERLAY_CONTROL_SPECS
from .interaction import CONTROL_SPECS as INTERACTION_CONTROL_SPECS
from .shell import CONTROL_SPECS as SHELL_CONTROL_SPECS
from .scopes import CONTROL_SPECS as SCOPE_CONTROL_SPECS
from .effects import CONTROL_SPECS as EFFECT_CONTROL_SPECS
from .tools import CONTROL_SPECS as TOOL_CONTROL_SPECS

__all__ = [
    "LAYOUT_CONTROL_SPECS",
    "DISPLAY_CONTROL_SPECS",
    "INPUT_CONTROL_SPECS",
    "DATA_CONTROL_SPECS",
    "NAVIGATION_CONTROL_SPECS",
    "OVERLAY_CONTROL_SPECS",
    "INTERACTION_CONTROL_SPECS",
    "SHELL_CONTROL_SPECS",
    "SCOPE_CONTROL_SPECS",
    "EFFECT_CONTROL_SPECS",
    "TOOL_CONTROL_SPECS",
]
