from __future__ import annotations

from .control import (
    TERMINAL_DEFAULT_ENGINE,
    TERMINAL_EVENTS,
    TERMINAL_MODULES,
    TERMINAL_REGISTRY_MANIFEST_LISTS,
    TERMINAL_REGISTRY_ROLE_ALIASES,
    TERMINAL_SCHEMA_VERSION,
    TERMINAL_STATES,
)

SCHEMA_VERSION = TERMINAL_SCHEMA_VERSION
DEFAULT_ENGINE = TERMINAL_DEFAULT_ENGINE
MODULES = tuple(sorted(TERMINAL_MODULES))
STATES = tuple(sorted(TERMINAL_STATES))
EVENTS = tuple(sorted(TERMINAL_EVENTS))
REGISTRY_ROLE_ALIASES = dict(TERMINAL_REGISTRY_ROLE_ALIASES)
REGISTRY_MANIFEST_LISTS = dict(TERMINAL_REGISTRY_MANIFEST_LISTS)
MODULE_ALIASES: dict[str, str] = {}

__all__ = [
    "SCHEMA_VERSION",
    "DEFAULT_ENGINE",
    "MODULES",
    "STATES",
    "EVENTS",
    "REGISTRY_ROLE_ALIASES",
    "REGISTRY_MANIFEST_LISTS",
    "MODULE_ALIASES",
]

