from __future__ import annotations

from ..schema import EVENTS as UMBRELLA_EVENTS
from ..schema import MODULES as UMBRELLA_MODULES

CONTROL_PREFIX = 'terminal'

MODULE_TOKENS = tuple(str(module) for module in UMBRELLA_MODULES)
MODULE_CANONICAL = MODULE_TOKENS
SUPPORTED_EVENTS = tuple(str(event) for event in UMBRELLA_EVENTS)

MODULE_CLASS_NAMES = {
    'capabilities': 'Capabilities',
    'command_builder': 'CommandBuilder',
    'execution_lane': 'ExecutionLane',
    'flow_gate': 'FlowGate',
    'log_panel': 'LogPanel',
    'log_viewer': 'LogViewer',
    'output_mapper': 'OutputMapper',
    'presets': 'Presets',
    'process_bridge': 'ProcessBridge',
    'progress': 'Progress',
    'progress_view': 'ProgressView',
    'prompt': 'Prompt',
    'raw_view': 'RawView',
    'replay': 'Replay',
    'session': 'Session',
    'stdin': 'Stdin',
    'stdin_injector': 'StdinInjector',
    'stream': 'Stream',
    'stream_view': 'StreamView',
    'tabs': 'Tabs',
    'timeline': 'Timeline',
    'view': 'View',
    'workbench': 'Workbench',
}

TERMINAL_COMMON_PAYLOAD_KEYS = {
    'context',
    'description',
    'enabled',
    'events',
    'icon',
    'label',
    'meta',
    'options',
    'payload',
    'state',
    'subtitle',
    'tags',
    'telemetry',
    'title',
    'variant',
    'visible',
}

TERMINAL_COMMON_PAYLOAD_TYPES = {
    'context': 'map',
    'description': 'string',
    'enabled': 'bool',
    'events': 'events',
    'icon': 'string',
    'label': 'string',
    'meta': 'map',
    'options': 'list',
    'payload': 'map',
    'state': 'state',
    'subtitle': 'string',
    'tags': 'list',
    'telemetry': 'map',
    'title': 'string',
    'variant': 'string',
    'visible': 'bool',
}

MODULE_ALLOWED_KEYS = {
    'capabilities': {
        'auto_scroll',
        'backend',
        'border_width',
        'bridge',
        'capabilities',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'lane',
        'line_height',
        'lines',
        'mapping',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'presets',
        'providers',
        'raw_text',
        'read_only',
        'session_id',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'command_builder': {
        'auto_scroll',
        'backend',
        'border_width',
        'bridge',
        'capabilities',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'lane',
        'line_height',
        'lines',
        'mapping',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'presets',
        'providers',
        'raw_text',
        'read_only',
        'session_id',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'execution_lane': {
        'auto_scroll',
        'backend',
        'border_width',
        'bridge',
        'capabilities',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'lane',
        'line_height',
        'lines',
        'mapping',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'presets',
        'providers',
        'raw_text',
        'read_only',
        'session_id',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'flow_gate': {
        'auto_scroll',
        'backend',
        'border_width',
        'bridge',
        'capabilities',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'lane',
        'line_height',
        'lines',
        'mapping',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'presets',
        'providers',
        'raw_text',
        'read_only',
        'session_id',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'log_panel': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'filters',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'log_viewer': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'filters',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'output_mapper': {
        'auto_scroll',
        'backend',
        'border_width',
        'bridge',
        'capabilities',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'lane',
        'line_height',
        'lines',
        'mapping',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'presets',
        'providers',
        'raw_text',
        'read_only',
        'session_id',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'presets': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'process_bridge': {
        'auto_scroll',
        'backend',
        'border_width',
        'bridge',
        'capabilities',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'lane',
        'line_height',
        'lines',
        'mapping',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'presets',
        'providers',
        'raw_text',
        'read_only',
        'session_id',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'progress': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'eta',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'indeterminate',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'percent',
        'progress',
        'raw_text',
        'read_only',
        'show_input',
        'stage',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'throughput',
        'title',
        'total',
        'value',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'progress_view': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'eta',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'indeterminate',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'percent',
        'progress',
        'raw_text',
        'read_only',
        'show_input',
        'stage',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'throughput',
        'title',
        'total',
        'value',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'prompt': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'placeholder',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'submit_label',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'raw_view': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'filters',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'replay': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'session': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'stdin': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'placeholder',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'submit_label',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'stdin_injector': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'placeholder',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'submit_label',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'stream': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'filters',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'stream_view': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'filters',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'tabs': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'timeline': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'eta',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'indeterminate',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'percent',
        'progress',
        'raw_text',
        'read_only',
        'show_input',
        'stage',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'throughput',
        'title',
        'total',
        'value',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'view': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'filters',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
    'workbench': {
        'auto_scroll',
        'border_width',
        'clear_on_submit',
        'command',
        'commands',
        'context',
        'cwd',
        'description',
        'enabled',
        'engine',
        'env',
        'events',
        'exit_code',
        'font_family',
        'font_size',
        'history',
        'icon',
        'input',
        'label',
        'line_height',
        'lines',
        'max_lines',
        'meta',
        'options',
        'output',
        'payload',
        'raw_text',
        'read_only',
        'show_input',
        'state',
        'status',
        'strip_ansi',
        'subtitle',
        'tags',
        'telemetry',
        'title',
        'variant',
        'visible',
        'webview_engine',
        'wrap_lines',
    },
}

MODULE_PAYLOAD_TYPES = {
    'capabilities': {
        'auto_scroll': 'bool',
        'backend': 'string',
        'border_width': 'num',
        'bridge': 'string',
        'capabilities': 'map',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'lane': 'string',
        'line_height': 'num',
        'lines': 'list',
        'mapping': 'map',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'presets': 'list',
        'providers': 'list',
        'raw_text': 'string',
        'read_only': 'bool',
        'session_id': 'string',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'command_builder': {
        'auto_scroll': 'bool',
        'backend': 'string',
        'border_width': 'num',
        'bridge': 'string',
        'capabilities': 'map',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'lane': 'string',
        'line_height': 'num',
        'lines': 'list',
        'mapping': 'map',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'presets': 'list',
        'providers': 'list',
        'raw_text': 'string',
        'read_only': 'bool',
        'session_id': 'string',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'execution_lane': {
        'auto_scroll': 'bool',
        'backend': 'string',
        'border_width': 'num',
        'bridge': 'string',
        'capabilities': 'map',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'lane': 'string',
        'line_height': 'num',
        'lines': 'list',
        'mapping': 'map',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'presets': 'list',
        'providers': 'list',
        'raw_text': 'string',
        'read_only': 'bool',
        'session_id': 'string',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'flow_gate': {
        'auto_scroll': 'bool',
        'backend': 'string',
        'border_width': 'num',
        'bridge': 'string',
        'capabilities': 'map',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'lane': 'string',
        'line_height': 'num',
        'lines': 'list',
        'mapping': 'map',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'presets': 'list',
        'providers': 'list',
        'raw_text': 'string',
        'read_only': 'bool',
        'session_id': 'string',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'log_panel': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'filters': 'any',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'log_viewer': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'filters': 'any',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'output_mapper': {
        'auto_scroll': 'bool',
        'backend': 'string',
        'border_width': 'num',
        'bridge': 'string',
        'capabilities': 'map',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'lane': 'string',
        'line_height': 'num',
        'lines': 'list',
        'mapping': 'map',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'presets': 'list',
        'providers': 'list',
        'raw_text': 'string',
        'read_only': 'bool',
        'session_id': 'string',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'presets': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'process_bridge': {
        'auto_scroll': 'bool',
        'backend': 'string',
        'border_width': 'num',
        'bridge': 'string',
        'capabilities': 'map',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'lane': 'string',
        'line_height': 'num',
        'lines': 'list',
        'mapping': 'map',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'presets': 'list',
        'providers': 'list',
        'raw_text': 'string',
        'read_only': 'bool',
        'session_id': 'string',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'progress': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'eta': 'string',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'indeterminate': 'bool',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'percent': 'num',
        'progress': 'num',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'stage': 'string',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'throughput': 'string',
        'title': 'string',
        'total': 'num',
        'value': 'any',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'progress_view': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'eta': 'string',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'indeterminate': 'bool',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'percent': 'num',
        'progress': 'num',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'stage': 'string',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'throughput': 'string',
        'title': 'string',
        'total': 'num',
        'value': 'any',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'prompt': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'placeholder': 'any',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'submit_label': 'any',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'raw_view': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'filters': 'any',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'replay': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'session': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'stdin': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'placeholder': 'any',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'submit_label': 'any',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'stdin_injector': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'placeholder': 'any',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'submit_label': 'any',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'stream': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'filters': 'any',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'stream_view': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'filters': 'any',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'tabs': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'timeline': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'eta': 'string',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'indeterminate': 'bool',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'percent': 'num',
        'progress': 'num',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'stage': 'string',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'throughput': 'string',
        'title': 'string',
        'total': 'num',
        'value': 'any',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'view': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'filters': 'any',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
    'workbench': {
        'auto_scroll': 'bool',
        'border_width': 'num',
        'clear_on_submit': 'bool',
        'command': 'string',
        'commands': 'list',
        'context': 'map',
        'cwd': 'string',
        'description': 'string',
        'enabled': 'bool',
        'engine': 'string',
        'env': 'map',
        'events': 'events',
        'exit_code': 'int',
        'font_family': 'string',
        'font_size': 'num',
        'history': 'list',
        'icon': 'string',
        'input': 'string',
        'label': 'string',
        'line_height': 'num',
        'lines': 'list',
        'max_lines': 'int',
        'meta': 'map',
        'options': 'list',
        'output': 'string',
        'payload': 'map',
        'raw_text': 'string',
        'read_only': 'bool',
        'show_input': 'bool',
        'state': 'state',
        'status': 'string',
        'strip_ansi': 'bool',
        'subtitle': 'string',
        'tags': 'list',
        'telemetry': 'map',
        'title': 'string',
        'variant': 'string',
        'visible': 'bool',
        'webview_engine': 'string',
        'wrap_lines': 'bool',
    },
}

MODULE_EVENTS = {
    'capabilities': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'command_builder': [
        'change',
        'command',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'execution_lane': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'flow_gate': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'log_panel': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'stream',
        'submit',
    ],
    'log_viewer': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'stream',
        'submit',
    ],
    'output_mapper': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'presets': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'process_bridge': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'progress': [
        'change',
        'input',
        'module_change',
        'output',
        'progress',
        'ready',
        'state_change',
        'submit',
    ],
    'progress_view': [
        'change',
        'input',
        'module_change',
        'output',
        'progress',
        'ready',
        'state_change',
        'submit',
    ],
    'prompt': [
        'change',
        'command',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'raw_view': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'stream',
        'submit',
    ],
    'replay': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'session': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'stdin': [
        'change',
        'command',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'stdin_injector': [
        'change',
        'command',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'stream': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'stream',
        'submit',
    ],
    'stream_view': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'stream',
        'submit',
    ],
    'tabs': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
    'timeline': [
        'change',
        'input',
        'module_change',
        'output',
        'progress',
        'ready',
        'state_change',
        'submit',
    ],
    'view': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'stream',
        'submit',
    ],
    'workbench': [
        'change',
        'input',
        'module_change',
        'output',
        'ready',
        'state_change',
        'submit',
    ],
}

MODULE_ACTIONS = {
    'capabilities': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'command_builder': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'execution_lane': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'flow_gate': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'log_panel': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'log_viewer': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'output_mapper': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'presets': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'process_bridge': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'progress': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_progress',
        'set_props',
        'set_read_only',
        'set_state',
        'set_total',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'progress_view': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_progress',
        'set_props',
        'set_read_only',
        'set_state',
        'set_total',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'prompt': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'raw_view': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'replay': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'session': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'stdin': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'stdin_injector': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'stream': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'stream_view': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'tabs': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'timeline': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'view': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
    'workbench': [
        'activate',
        'append',
        'append_lines',
        'blur',
        'clear',
        'emit',
        'emit_change',
        'focus',
        'get_buffer',
        'get_input',
        'get_state',
        'get_value',
        'register_backend',
        'register_bridge',
        'register_command',
        'register_module',
        'register_panel',
        'register_provider',
        'register_tool',
        'register_view',
        'set_input',
        'set_module',
        'set_payload',
        'set_props',
        'set_read_only',
        'set_state',
        'set_value',
        'submit',
        'trigger',
        'write',
    ],
}

__all__ = [
    "CONTROL_PREFIX",
    "MODULE_TOKENS",
    "MODULE_CANONICAL",
    "SUPPORTED_EVENTS",
    "MODULE_CLASS_NAMES",
    "TERMINAL_COMMON_PAYLOAD_KEYS",
    "TERMINAL_COMMON_PAYLOAD_TYPES",
    "MODULE_ALLOWED_KEYS",
    "MODULE_PAYLOAD_TYPES",
    "MODULE_EVENTS",
    "MODULE_ACTIONS",
]
