from __future__ import annotations

from .control import (
    STUDIO_EVENTS,
    STUDIO_MODULE_ALIASES,
    STUDIO_MODULES,
    STUDIO_REGISTRY_MANIFEST_LISTS,
    STUDIO_REGISTRY_ROLE_ALIASES,
    STUDIO_SCHEMA_VERSION,
    STUDIO_STATES,
)

SCHEMA_VERSION = STUDIO_SCHEMA_VERSION
MODULES = tuple(sorted(STUDIO_MODULES))
MODULE_ALIASES = dict(STUDIO_MODULE_ALIASES)
STATES = tuple(sorted(STUDIO_STATES))
EVENTS = tuple(sorted(STUDIO_EVENTS))
REGISTRY_ROLE_ALIASES = dict(STUDIO_REGISTRY_ROLE_ALIASES)
REGISTRY_MANIFEST_LISTS = dict(STUDIO_REGISTRY_MANIFEST_LISTS)

__all__ = [
    "SCHEMA_VERSION",
    "MODULES",
    "MODULE_ALIASES",
    "STATES",
    "EVENTS",
    "REGISTRY_ROLE_ALIASES",
    "REGISTRY_MANIFEST_LISTS",
]
